# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Location of .github/workflows
    directory: "/"
    schedule:
      interval: "weekly"

  # Maintain dependencies for Maven
  - package-ecosystem: "maven"
    # Location of topmost pom.xml
    directory: "/"
    schedule:
      interval: "weekly"

   ignore:
   # Ignore all patch updates
   - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
