# Builds SemTK on every pull request/push (while ignoring tag-only pushes):

name: SemTK continuous build

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out SemTK source
      uses: actions/checkout@v3

    - name: Cache local Maven repository
      uses: actions/cache@v3.3.2
      with:
        path: ~/.m2/repository
        key: maven-${{ hashFiles('**/pom.xml') }}

    - name: Build SemTK source
      # TODO: The tests currently fail in Github Actions
      run: |
        mvn -version
        mvn -B package -DskipTests -pl '!standaloneExecutables,!distribution'
