# Run on every pull request or push (except tag-only pushes).
# Build SemTK with Java and Maven.
# Cache/restore dependencies to improve execution time.
# Publish SemTK SNAPSHOT version to GitHub Packages.
# https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: SemTK Integration Workflow
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
  push:
    branches-ignore: [ 'dependabot/**' ]
    tags-ignore: [ '**' ]

jobs:
  build:
    permissions:
      contents: read
      packages: write
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        distribution: [ temurin ]
        java-version: [ 11 ]
        os: [ ubuntu-20.04 ]

    steps:
    - name: Check out SemTK source
      uses: actions/checkout@v3

    - name: Set up Java and Maven
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: ${{ matrix.distribution }}
        java-version: ${{ matrix.java-version }}
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build SemTK source
      # Note the tests currently fail in GitHub Actions
      run: mvn -B package -DskipTests -pl '!standaloneExecutables,!distribution'

    - name: Publish SemTK SNAPSHOT to GitHub Packages
      # Uncomment after deploy works
      #if: github.ref == 'refs/heads/master'
      run: mvn -B deploy -pl '!standaloneExecutables,!distribution' -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
